 menuc8205c7636e728d448c2774e6a4a944b = {     {"Avahi SSH服务器浏览器", "/usr/bin/bssh", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC服务器浏览器", "/usr/bin/bvnc", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Ekiga 软电话", "ekiga", "/usr/share//icons/hicolor/16x16/apps/ekiga.png" },
     {"Empathy", "empathy", "/usr/share//icons/hicolor/16x16/apps/empathy.png" },
     {"Firefox", "firefox ", "/usr/share//icons/hicolor/16x16/apps/firefox.png" },
     {"Thunderbird", "thunderbird ", "/usr/share//icons/hicolor/16x16/apps/thunderbird.png" },
     {"Web", "epiphany ", "/usr/share//icons/gnome/16x16/apps/web-browser.png" },
     {"信使(iptux)", "iptux", "/usr/share//icons/hicolor/16x16/apps/ip-tux.png" },
     {"远程桌面查看器", "vinagre ", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-remote-desktop.png" },
 }

 menudb53804b7d726967c58fcc8c9ca03d27 = {     {"Evolution", "evolution ", "/usr/share//icons/hicolor/16x16/apps/evolution.png" },
     {"LibreOffice ", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"字典", "gnome-dictionary", "/usr/share//icons/gnome/16x16/apps/accessories-dictionary.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
 }

 menue1b7cee794666669f55acead93513971 = {     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"gThumb", "gthumb ", "/usr/share//icons/hicolor/16x16/apps/gthumb.png" },
     {"图像查看器", "eog ", "/usr/share//icons/hicolor/16x16/apps/eog.png" },
     {"图像查看器", "gpicview ", "/usr/share/pixmaps/gpicview.png" },
 }

 menu526fe18cc54d217db3fdb0bf6c5e9bc8 = {     {"Audio Mixer", "xfce4-mixer", "/usr/share//icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Brasero", "brasero ", "/usr/share//icons/hicolor/16x16/apps/brasero.png" },
     {"OSD Lyrics", "osdlyrics", "/usr/share//icons/hicolor/64x64/apps/osdlyrics.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share//icons/hicolor/16x16/apps/smplayer.png" },
     {"guvcview", "guvcview", "///usr/share/pixmaps/guvcview/guvcview.png" },
     {"录音机", "gnome-sound-recorder", "/usr/share//icons/hicolor/16x16/apps/gnome-sound-recorder.png" },
     {"茄子", "cheese", "/usr/share//icons/hicolor/16x16/apps/cheese.png" },
     {"视频", "totem ", "/usr/share//icons/hicolor/16x16/apps/totem.png" },
     {"音乐榨汁机", "sound-juicer ", "/usr/share//icons/hicolor/16x16/apps/sound-juicer.png" },
 }

 menuba08216f13dd1742157412386eee1225 = {     {"俄罗斯方块", "quadrapassel", "/usr/share//icons/hicolor/16x16/apps/quadrapassel.png" },
     {"关灯", "lightsoff"},
     {"华容道", "gnotski", "/usr/share//icons/hicolor/16x16/apps/gnotski.png" },
     {"四子连线", "gnect", "/usr/share//icons/hicolor/16x16/apps/gnect.png" },
     {"四邻", "gnotravex", "/usr/share//icons/hicolor/16x16/apps/gnotravex.png" },
     {"国际象棋", "glchess", "/usr/share//icons/hicolor/16x16/apps/glchess.png" },
     {"对对碰", "gnome-mahjongg", "/usr/share//icons/hicolor/16x16/apps/gnome-mahjongg.png" },
     {"扫雷", "gnomine", "/usr/share//icons/hicolor/16x16/apps/gnomine.png" },
     {"掷骰子", "gtali", "/usr/share//icons/hicolor/16x16/apps/gtali.png" },
     {"数独", "gnome-sudoku", "/usr/share//icons/hicolor/16x16/apps/gnome-sudoku.png" },
     {"机器人", "gnobots2", "/usr/share//icons/hicolor/16x16/apps/gnobots2.png" },
     {"消色块", "swell-foop", "/usr/share//icons/hicolor/16x16/apps/swell-foop.png" },
     {"空当接龙", "sol --freecell", "/usr/share//icons/hicolor/16x16/apps/gnome-freecell.png" },
     {"纸牌王", "sol", "/usr/share//icons/hicolor/16x16/apps/gnome-aisleriot.png" },
     {"贪食蛇", "gnibbles", "/usr/share//icons/hicolor/16x16/apps/gnibbles.png" },
     {"连珠消球", "glines", "/usr/share//icons/hicolor/16x16/apps/glines.png" },
     {"黑白棋", "iagno", "/usr/share//icons/hicolor/16x16/apps/iagno.png" },
 }

 menude71492af019157e5a5ef958b570e760 = {     {"Avahi Zero浏览器", "/usr/bin/avahi-discover", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Fcitx", "fcitx", "/usr/share//icons/hicolor/16x16/apps/fcitx.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share//icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Terminator", "terminator", "/usr/share//icons/hicolor/16x16/apps/terminator.png" },
     {"Thunar 文件管理器", "thunar ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"XArchive Manager", "xarchive ", "///usr/share/pixmaps/xarchive.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf 系统配置编辑器", "dconf-editor", "/usr/share//icons/hicolor/32x32/apps/dconf-editor.png" },
     {"urxvt", "urxvt", "/usr/share//icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share//icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share//icons/gnome/16x16/apps/terminal.png" },
     {"批量重命名", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"磁盘使用分析器", "baobab", "/usr/share//icons/hicolor/16x16/apps/baobab.png" },
     {"系统日志", "gnome-system-log", "/usr/share//icons/hicolor/16x16/apps/logview.png" },
     {"系统监视器", "gnome-system-monitor", "/usr/share//icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"配置编辑器", "gconf-editor", "/usr/share//icons/hicolor/16x16/apps/gconf-editor.png" },
 }

 menu41282bf95e43c64d579757573a03cdde = {     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"Eclipse", "eclipse", "/usr/share//icons/hicolor/32x32/apps/eclipse.png" },
     {"Meld", "meld ", "/usr/share//icons/hicolor/16x16/apps/meld.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share//icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share//icons/hicolor/16x16/apps/java.png" },
     {"Qt Assistant", "/usr/bin/assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/bin/designer", "/usr/share//icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/bin/linguist", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
 }

 menu3b6fab8ae1a5e1bef9fa2320d64c4c2a = {     {"Caribou", "caribou"},
     {"Dasher", "dasher", "/usr/share//icons/hicolor/48x48/apps/dasher.png" },
     {"Orca", "orca --replace", "/usr/share//icons/hicolor/16x16/apps/orca.png" },
 }

 menuc9a6ee90f5d43732e3f6cf4dcaa8493c = {     {"7-Zip FM", "7zFM", "/usr/share//icons/hicolor/32x32/apps/p7zip.png" },
     {"Caribou", "caribou"},
     {"Dasher", "dasher", "/usr/share//icons/hicolor/48x48/apps/dasher.png" },
     {"Orca", "orca --replace", "/usr/share//icons/hicolor/16x16/apps/orca.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"gedit", "gedit ", "/usr/share//icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"主菜单", "alacarte", "/usr/share//icons/hicolor/16x16/apps/alacarte.png" },
     {"图像查看器", "gpicview ", "/usr/share/pixmaps/gpicview.png" },
     {"字体查看器", "gnome-font-viewer ", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"字符映射表", "gucharmap", "/usr/share//icons/gnome/16x16/apps/accessories-character-map.png" },
     {"密码和密钥", "/usr/bin/seahorse", "/usr/share//icons/hicolor/16x16/apps/seahorse.png" },
     {"应用程序查找器", "xfce4-appfinder", "/usr/share//icons/gnome/16x16/actions/gtk-find.png" },
     {"归档管理器", "file-roller ", "/usr/share//icons/hicolor/16x16/apps/file-roller.png" },
     {"截图", "gnome-screenshot --interactive", "/usr/share//icons/gnome/16x16/apps/applets-screenshooter.png" },
     {"搜索文件...", "gnome-search-tool", "/usr/share//icons/gnome/16x16/actions/system-search.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"桌面搜索", "tracker-needle", "/usr/share//icons/gnome/16x16/actions/system-search.png" },
     {"磁盘", "gnome-disks", "/usr/share//icons/hicolor/16x16/apps/gnome-disks.png" },
     {"终端", "gnome-terminal", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"计算器", "gcalctool", "/usr/share//icons/gnome/16x16/apps/accessories-calculator.png" },
     {"阿帖便笺", "tomboy --search", "/usr/share//icons/hicolor/16x16/apps/tomboy.png" },
 }

xdgmenu = {    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"办公", menudb53804b7d726967c58fcc8c9ca03d27},
    {"图像", menue1b7cee794666669f55acead93513971},
    {"影音", menu526fe18cc54d217db3fdb0bf6c5e9bc8},
    {"游戏", menuba08216f13dd1742157412386eee1225},
    {"系统工具", menude71492af019157e5a5ef958b570e760},
    {"编程", menu41282bf95e43c64d579757573a03cdde},
    {"辅助功能", menu3b6fab8ae1a5e1bef9fa2320d64c4c2a},
    {"附件", menuc9a6ee90f5d43732e3f6cf4dcaa8493c},
}

